"""initial migration

Revision ID: c9e99212760e
Revises: 59063fb8b374
Create Date: 2025-04-26 20:38:36.752030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9e99212760e'
down_revision = '59063fb8b374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluaciones', sa.Column('fecha_evaluacion', sa.DateTime(), nullable=True))
    op.alter_column('evaluaciones', 'tiempo_respuesta',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('evaluaciones', 'errores_ortograficos',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('evaluaciones', 'repeticiones',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('evaluaciones', 'comprension_lectora',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('evaluaciones', 'ejercicio_dictado',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('evaluaciones', 'ejercicio_lectura',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('evaluaciones', 'ejercicio_comprension',
               existing_type=sa.VARCHAR(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('evaluaciones', 'prediccion',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('evaluaciones', 'confianza_prediccion',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.drop_index('ix_evaluaciones_id', table_name='evaluaciones')
    op.drop_column('evaluaciones', 'edad')
    op.drop_column('evaluaciones', 'fecha_creacion')
    op.drop_column('evaluaciones', 'genero')
    op.drop_column('evaluaciones', 'nivel_educativo')
    op.drop_column('evaluaciones', 'id_usuario')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluaciones', sa.Column('id_usuario', sa.INTEGER(), nullable=True))
    op.add_column('evaluaciones', sa.Column('nivel_educativo', sa.VARCHAR(), nullable=True))
    op.add_column('evaluaciones', sa.Column('genero', sa.VARCHAR(), nullable=True))
    op.add_column('evaluaciones', sa.Column('fecha_creacion', sa.DATETIME(), nullable=True))
    op.add_column('evaluaciones', sa.Column('edad', sa.INTEGER(), nullable=True))
    op.create_index('ix_evaluaciones_id', 'evaluaciones', ['id'], unique=False)
    op.alter_column('evaluaciones', 'confianza_prediccion',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('evaluaciones', 'prediccion',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('evaluaciones', 'ejercicio_comprension',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('evaluaciones', 'ejercicio_lectura',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('evaluaciones', 'ejercicio_dictado',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('evaluaciones', 'comprension_lectora',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('evaluaciones', 'repeticiones',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('evaluaciones', 'errores_ortograficos',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('evaluaciones', 'tiempo_respuesta',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.drop_column('evaluaciones', 'fecha_evaluacion')
    # ### end Alembic commands ###
