"""initial migration

Revision ID: 59063fb8b374
Revises: 
Create Date: 2025-04-25 21:19:40.920366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59063fb8b374'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tiempo_respuesta', sa.Float(), nullable=True),
    sa.Column('errores_ortograficos', sa.Integer(), nullable=True),
    sa.Column('repeticiones', sa.Integer(), nullable=True),
    sa.Column('comprension_lectora', sa.Float(), nullable=True),
    sa.Column('ejercicio_dictado', sa.String(), nullable=True),
    sa.Column('ejercicio_lectura', sa.String(), nullable=True),
    sa.Column('ejercicio_comprension', sa.String(), nullable=True),
    sa.Column('prediccion', sa.Boolean(), nullable=True),
    sa.Column('confianza_prediccion', sa.Float(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('genero', sa.String(), nullable=True),
    sa.Column('nivel_educativo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluaciones_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluaciones_id'))

    op.drop_table('evaluaciones')
    # ### end Alembic commands ###
